name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1.1
      with:
        envkey_DEBUG: ${{ secrets.DEBUG }}
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        envkey_REDIS_SERVER: ${{ secrets.REDIS_SERVER }}
        envkey_REDIS_HOST: ${{ secrets.REDIS_HOST }}
        envkey_REDIS_PORT: ${{ secrets.REDIS_PORT }}
        github_workspace: ${{ github.workspace }}
    - name: Run Tests
      run: |
        cd ALIVEcode
        python manage.py test
